spring:
  rabbitmq:
    host: 192.168.0.7
  datasource:
    url: jdbc:postgresql://localhost:5432/Weather
    username: postgres
    password: colonel
    initialize: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
